### ISSUE TITLE
Floating blocks aren't completely fixed in this version

### ISSUE THREAD

**Issue by Zachary2897** [Diamondman121314/TinkersAether#1]
https://github.com/Diamondman121314/TinkersAether/blob/3c097588ee57244b760a042faa6b9ad304a2f6fd/src/main/java/shnupbups/tinkersaether/traits/Antigrav.java#L41

This line needs to be removed, otherwise floating blocks created with Tinkers' tools will still disappear instantly.

Relevant code from my repo (I've confirmed that this completely fixes the issue): https://github.com/Zachary2897/TinkersAether/blob/3fb8ebc8c9e195d9c76ac8d9df8da776bda18312/src/main/java/shnupbups/tinkersaether/traits/Antigrav.java#L38

**Comment by Diamondman121314** [comment]
Apologies, I just saw this now as I guess I never got a notification from this. I'll fix it now!
